### ISSUE TITLE
undefined error

### ISSUE THREAD

**Issue by slicken** [CoinCircle/go-etherdelta#4]
Hi.
I am getting this error in etherdelta.go running the examples in folder
" ../etherdelta.go:602:12: undefined: "github.com/ethereum/go-ethereum/crypto".ToECDSAPub "
something with row 602: pubKey := crypto.ToECDSAPub(recoveredPub)

Regards,

**Comment by MathieuGilbert** [comment]
@slicken Have a look at the PR here: https://github.com/CoinCircle/go-etherdelta/pull/5
